<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AfshasPc" failures="1" tests="4" name="SauceDemoTests" time="82.712" errors="0" timestamp="2025-09-01T11:27:52 IST">
  <testcase classname="com.capstone.tests.LoginTest" name="loginWithInvalidUser" time="8.328"/>
  <testcase classname="com.capstone.tests.LoginTest" name="loginWithValidUser" time="10.281"/>
  <testcase classname="com.capstone.tests.CartTest" name="openChekoutPage" time="14.442"/>
  <testcase classname="com.capstone.tests.CheckoutTest" name="completeCheckoutFlow" time="26.757">
    <failure type="java.lang.AssertionError" message="expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]">
      <![CDATA[java.lang.AssertionError: expected [THANK YOU FOR YOUR ORDER] but found [Thank you for your order!]
at com.capstone.tests.CheckoutTest.completeCheckoutFlow(CheckoutTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- completeCheckoutFlow -->
</testsuite> <!-- SauceDemoTests -->
